# Generated by Django 5.1.1 on 2024-09-15 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VMs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_computador', models.CharField(max_length=255)),
                ('nome_de_usuario', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('resolucao', models.CharField(blank=True, max_length=50, null=True)),
                ('usar_todos_os_monitores', models.BooleanField(default=False)),
                ('area_de_transferencia', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RPAs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_robo', models.CharField(max_length=255)),
                ('unidade', models.CharField(max_length=255)),
                ('agendador', models.BooleanField(default=False)),
                ('area_de_trabalho', models.IntegerField(default=1)),
                ('maquina_virtual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robos', to='gerenciador_vm.vms')),
            ],
        ),
    ]
