# Generated by Django 5.1.1 on 2024-09-15 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_vm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VMs',
            new_name='Maquinas_Virtuais',
        ),
        migrations.RenameModel(
            old_name='RPAs',
            new_name='Robotizacoes',
        ),
    ]
