# Generated by Django 5.1.1 on 2024-09-16 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_vm', '0002_rename_vms_maquinas_virtuais_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maquinas_virtuais',
            options={'verbose_name': 'Máquina Virtual', 'verbose_name_plural': 'Máquinas Virtuais'},
        ),
        migrations.AlterModelOptions(
            name='robotizacoes',
            options={'verbose_name': 'Robotização', 'verbose_name_plural': 'Robotizações'},
        ),
        migrations.CreateModel(
            name='VMProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('maquina_virtual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciador_vm.maquinas_virtuais')),
            ],
        ),
    ]
