# Generated by Django 5.1.1 on 2024-09-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_vm', '0003_alter_maquinas_virtuais_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmprocesso',
            name='nome_usuario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
