# Generated by Django 5.1.1 on 2024-09-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_vm', '0004_vmprocesso_nome_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robotizacoes',
            name='area_de_trabalho',
        ),
        migrations.AddField(
            model_name='maquinas_virtuais',
            name='area_de_trabalho',
            field=models.IntegerField(default=1),
        ),
    ]
