# Generated by Django 5.1.1 on 2024-10-31 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_vm', '0005_remove_robotizacoes_area_de_trabalho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinas_virtuais',
            name='favoritada',
            field=models.BooleanField(default=False),
        ),
    ]
